trigger:
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@1
  inputs:
    version: '20.x'
  displayName: 'Install Node.js'

- script: |
    git config --global user.email "bot@dot-website.com"
    git config --global user.name "Dot Website CI"
    git config --global push.autoSetupRemote true
  displayName: 'Configure Git for CI'

- script: |
    npm install -g pnpm
    npm install -g @vscode/vsce
  displayName: 'Install pnpm'

- script: |
    pnpm install
  displayName: 'Install dependencies'

- script: |
    pnpm build
    pnpm package
  displayName: 'Build and package VSIX file'

- script: |
    if [ "$(Build.Reason)" == "PullRequest" ]; then
      echo "This is a PR merge, incrementing minor version..."
      bumpp minor --commit --tag --push --message "Bump minor version to %s [skip ci]"
    else
      echo "Direct push to master, incrementing patch version..."
      bumpp patch --commit --tag --push --message "Bump patch version to %s [skip ci]"
    fi
    VERSION=$(node -p "require('./package.json').version")
    echo "##vso[task.setvariable variable=ExtensionVersion]$VERSION"
  displayName: 'Bump minor/patch version'
  env:
    NODE_AUTH_TOKEN: $(vsceAuthToken)

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: './dot-website-$(ExtensionVersion).vsix'
    artifactName: 'dot-website-$(ExtensionVersion)'
    publishLocation: 'pipeline'
  displayName: 'Publish VSIX artifact'

- script: |
    vsce publish --no-dependencies --version $(ExtensionVersion)
  displayName: 'Publish to VS Code Marketplace'
  env:
    VSCE_PAT: $(VSCE_PAT)
    NODE_AUTH_TOKEN: $(vsceAuthToken) # npm authentication token for vsce to authenticate with npm registry
