trigger:
  branches:
    include:
    - master

pr: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  PNPM_STORE_PATH: $(Pipeline.Workspace)/.pnpm-store  # Use a shared pnpm store path in the pipeline

steps:
- task: UseNode@1
  inputs:
    version: '20.x'
  displayName: 'Install Node.js'

- task: Cache@2
  inputs:
    key: 'pnpm | "$(Agent.OS)" | pnpm-lock.yaml'
    restoreKeys: |
      pnpm | "$(Agent.OS)"
    path: $(PNPM_STORE_PATH)  # Cache the pnpm store path
  displayName: Cache pnpm store

- script: |
    git config --global user.email "bot@dot-website.com"
    git config --global user.name "Dot Website CI"
    git config --global push.autoSetupRemote true
  displayName: 'Configure Git for CI'

- script: |
    npm install -g pnpm
    npm install -g @vscode/vsce
    npm install -g bumpp
  displayName: 'Install pnpm, vsce, and bumpp'

- script: |
    pnpm config set store-dir $(PNPM_STORE_PATH)  # Set the pnpm store directory to a specific path
    pnpm install
  displayName: 'Install dependencies'
  env:
    PNPM_STORE_PATH: $(PNPM_STORE_PATH)

- script: |
    pnpm build
    pnpm package
  displayName: 'Build and package VSIX file'

- script: |
    set -x  # Enable detailed logging for the script
    if [ "$(Build.Reason)" == "PullRequest" ]; then
      echo "This is a PR merge, incrementing minor version..."
      bumpp minor --commit --tag --push --message "Bump minor version to %s [skip ci]" --yes
    else
      echo "Direct push to master, incrementing patch version..."
      bumpp patch --commit --tag --push --message "Bump patch version to %s [skip ci]" --yes
    fi
    VERSION=$(node -p "require('./package.json').version")
    echo "##vso[task.setvariable variable=ExtensionVersion]$VERSION"
  displayName: 'Bump minor/patch version'
  timeoutInMinutes: 10  # Timeout after 10 minutes to avoid long hangs
  env:
    NODE_AUTH_TOKEN: $(vsceAuthToken)

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: './dot-website-$(ExtensionVersion).vsix'
    artifactName: 'dot-website-$(ExtensionVersion)'
    publishLocation: 'pipeline'
  displayName: 'Publish VSIX artifact'

- script: |
    set -x  # Enable verbose output for the script
    echo "Publishing extension v$(ExtensionVersion) to VS Code Marketplace..."
    vsce publish --no-dependencies --allow-missing-repository --version $(ExtensionVersion) --pat $(VSCE_PAT) --verbose
    echo "vsce publish command completed."
  displayName: 'Publish to VS Code Marketplace'
  env:
    VSCE_PAT: $(VSCE_PAT)
    NODE_AUTH_TOKEN: $(vsceAuthToken)
